---
title: "Pengenalan bahasa pemrograman R: untuk non-programmer"
author: "Dasapta Erwin Irawan dan Prana Ugi"
date: "August 23, 2015"
output:
  pdf_document:
    toc: true
    number_sections: true
---


Berikut ini adalah outline buku ini

# BAB 1 PENDAHULUAN

## Sekilas R
Menjelaskan sekilas mengenai R.

## Sejarah R
Menjelaskan sekilas tentang awal pembuatan R dan perkembangannya.

## Mengapa R
Mengapa banyak saintis menggunakan R? Dapat dibaca di bab ini beberapa karakter R yang gratis, open source dan cross platfotm (Linux, Mac, Windows); bagaimana R mendukung prinsip _reproducibility_ dan dapat menghasilkan output grafis yang cantik dan dapat dikustomisasi sesuai keperluan.

### R gratis, _open source_, dan _cross platform_
### R mendukung prinsip _reproducibility_
### R menghasilkan visualisasi yang berkualitas tinggi 

## Mengenal Lingkungan R
R terdiri dari R base dan R Studio IDE. Ada R code, ada R package. Apakah itu semua? Anda dapat membacanya di bab ini

## Instalasi R
Bab ini menjelaskan secara singkat bagaimana menginstalasi R di PC atau laptop anda.

## Menggunakan buku ini
Bab ini menjelaskan bagaimana sebaiknya anda menggunakan buku ini sebagai panduan.

# BAB 2 PREPARASI DAN MANIPULASI DATA DALAM R

Data adalah salah satu bagian sentral dari R, bagian yang lainnya adalah kode dan output. Oleh karenanya kami menempatkan bagaimana menyiapkan dan memanipulasi data di bab kedua. Dalam diagram berikut ini dapat anda lihat bahwa mekanisme kerja dalam R adalah: 

- input: berupa data
- proses: berupa kumpulan kode perintah
- output: berupa tabel dan plot


# BAB 3 BAHASA R

Anda harus memahami bahasa R sebelum dapat membuat perintah kode dalam R. Bahasa R menurut kami sangat mudah dipahami karena sudah dikemas di dalam berbagai fungsi siap pakai. Anda tinggal menggunakannya dengan berbagai argumen yang diperlukan sesuai kebutuhan. 

Bab ini akan membahas bagaimana anda memanfaatkan fungsi dan argumen untuk membantu anda menganalisis data. Dasar-dasar format (syntax) kode perintah dalam R akan disampaikan dengan beberapa contoh aplikatif.

Fungsi (_fungctions_)



Argumen (_arguments_)






# BAB 4


# BAB 5


# BAB 6


# BAB 7


# BAB 8


# BAB 9


# BAB 10 BEBERAPA CONTOH KODE PROGRAM R
Beberapa contoh kode program untuk analisis dasar dan analisis statistik diberikan pada bab ini.

## Manipulasi tabel/data frame
## Analisis deskriptif
## Plotting
## Analisis korelasi
## Analisis spasial


# DAFTAR PUSTAKA

https://www.rochester.edu/college/psc/thestarlab/help/rcourse/R-Course.pdf

http://www2.ims.nus.edu.sg/preprints/2006-34.pdf

https://www3.nd.edu/~mclark19/learn/Introduction_to_R.pdf

http://data.princeton.edu/R/introducingR.pdf




