---
title: "Pengenalan bahasa pemrograman R: untuk non-programmer"
author: "Dasapta Erwin Irawan dan Prana Ugi"
date: "August 23, 2015"
output:
  pdf_document:
    toc: true
    number_sections: true
---


# BAB 1 PENDAHULUAN

## Sekilas R

Beberapa tahun yang lalu, kalau anda melihat huruf "R", maka anda akan memikirkan alfabet ke-18. Tapi saat ini "R" juga bisa berarti bahasa pemrograman yang  trendi. R kini telah memiliki lebih dari 4000 paket tambahan (_add-on package_) atau biasa disebut _package_ saja, masing-masing _package_ tersebut umumnya memiliki _miling list_ dengan anggota ribuan, selain itu juga ada banyak sekali R group di media sosial seperti Google+, LinkedIn, dan Twitter. Situs [R-evolution](http://blog.revolutionanalytics.com/2013/05/how-r-grows.html) menampilkan jumlah package yang diunggah tiap tahun dan grafik para pengembang yang membuat lebih dari 10 package.   

Saat ini juga rutin diadakan pertemuan pengguna R di berbagai negara yang disebut R _Meetup_. Saat ini telah diadakan 155 pertemuan dengan jumlah peserta 46.607, di 127 kota di 31 negara, menurut situs [R user group](http://r-users-group.meetup.com/). 

R yang awalnya diperuntukkan untuk analisis statistik, saat ini telah berkembang aplikasinya hingga dapat melakukan manipulasi data GIS serta menampilkannya. Ditambah lagi dengan era _data analysis_ atau akrab disebut _big data_, maka perkembangan R menjadi tidak terbendung lagi.

Aplikasi R yang terus meluas didukung oleh berkembangnya bahasa pemrograman lainnya, seperti python, Ruby dll. Salah satu contohnya adalah R markdown. Bahasa _markup_ (_markup language_) yang lebih mudah dari LaTeX atau html sekalipun. Dengan menggunakan R markdown, saat ini anda bahwa bisa membuat _blogpost_ atau naskah buku dengan R, seperti halnya naskah yang sedang anda baca saat ini. Penjelasan lebih detail mengenai Markdown akan saya jelaskan dalam bagian yang lain.

## Sejarah R

Menurut situs [R project](http://www.r-project.org/) R adalah bahasa dan lingkungan untuk komputasi statistik dan grafis. R adalah proyek berjenis _open source_ GNU, mirip dengan bahasa "S" yang dikembangkan oleh Bell Laboratories (dulu dikenal sebagai AT&T, sekarang bernama Lucent Technologies) oleh John Chambers dkk. Sekarang anda tahu kan bahwa R bukanlah satu-satunya bahasa pemrograman yang bernama unik. 

Perintah dasar dalam bahasa R telah menyediakan berbagai _tool_ untuk pemodelan statistik linear dan nonlinear, analisis _time-series_, klasifikasi, analisis klaster, dan analisis grafis. Kemampuan ini terus berkembang dengan adanya ribuan paket tambahan yang diunggah ke server CRAN tiap tahunnya. 

Testimoni dari para pengembang dan pengguna R menyebutkan bahwa salah satu kelebihannya adalah sifatnya yang dapat diulang (_reproducible_) dan mampu menghasilkan keluaran grafis berkualitas tinggi untuk keperluan publikasi ilmiah. Jadi mengapa anda tidak belajar mulai sekarang. Anda tidak akan sendiri karena kesulitan anda pasti ada jawabnya.  

## Mengapa R

Mengapa orang menggunakan R? Beberapa alasannya adalah sebagai berikut.

### R gratis, _open source_, dan _cross platform_

Alasan utama pasti karena gratis. Tidak hanya gratis tapi juga _open source_. Apa artinya? Kita tidak hanya bisa membuat paket tambahan saja, tetapi juga bisa memodifikasi kode dasar R. Tentunya ini diperuntukkan bagi yang memahami dasar pemrograman atau yang memang profesinya sebagai pengembang (_developer_). Namun demikian, dengan banyaknya paket tambahan R, maka mestinya sudah banyak pula tutorial untuk membuatnya. Bahkan saat ini, saya memperhatikan, kebanyakan mahasiswa master atau PhD di luar negeri yang menggunakaan statistik dan R dalam risetnya, membuat _package_ sendiri sesuai kebutuhan risetnya. R juga tersedia untuk tiga sistem operasi mayor atau istilah kerennya _cross platform_, yaitu: Linux (Ubuntu, Fedora), Mac OS, dan Windows. 

### R mendukung prinsip _reproducibility_

R adalah aplikasi berbasis _command line_, artinya setiap perintah harus diketik sebagai baris perintah. Tidak seperti SPSS, Statistica, atau Minitab, yang berbasis _point and click_ serta _drag and drop_. Karena menggunakan baris perintah, maka anda dapat berbagi hasil analisis dengan mudah, cukup dengan mengirimkan baris kode perintah dan datasetnya. Dengan menjalankan ulang baris perintah terhadap dataset tersebut, maka orang lain, misal rekan kerja anda, dapat mengulang proses dan analisis yang anda kerjakan secara persis sama. Prinsip ini disebut sebagai _reproducibility_. Anda tidak perlu mengirimkan _screenshot_ layar dan grafik berformat jpeg hanya untuk menjelaskan proses yang anda kerjakan dan hasilnya. Rekan kerja anda pun cukup meng-_copy paste_ kode perintah ke dalam layar R Studio atau R base-nya. Apakah R Studio dan R base itu. Akan dijelaskan tidak lama lagi.

### R menghasilkan visualisasi yang berkualitas tinggi 

R juga mendukung para peneliti untuk membuat grafik yang berkualitas baik, atau biasa disebit _publication quality images_. Ini karena redaksi jurnal ilmiah biasanya mensyaratkan resolusi dan format grafik khusus, yang tidak dapat dibuat dengan menggunakan piranti lunak _spreadsheet_ biasa seperti Ms Excel atau LibreOffice Sheet. Fasilitas ini tentu saja sangat membantu kita yang berprofesi sebagai dosen dan peneliti. Visualisasi yang dapat dibuat dengan R, tapi tidak dengan Excel, misalnya: 

+ menyandingkan dua atau lebih grafik dengan format sumbu yang sama. Cara yang biasa dilakukan adalah meng-copy beberapa grafik dan menempelkannya secara manual. Akibatnya format sumbu, kisaran nilai maks dan min dapat saja berbeda. 
+ menampilkan identitas data pada grafik. Excel hanya dapat memunculkan nilai sumbu x atau y, tapi tidak dapat menampilkan identitas data.

## Mengenal Lingkungan R

R bukan hanya sebuah bahasa pemrograman. Ia adalah lingkungan pengembangan terintegrasi (_integrated development environment_ atau sering disingkat IDE). Beberapa komponen penyusun R dapat dijelaskan secara singkat sebagai berikut:

+ __R base__: ini adalah inti dari instalasi R. Tanpa menginstalasi komponen ini, R tidak akan berjalan dalam sistem anda. R base sudah memiliki perangkat (_tools_) yang lengkap untuk keperluan analisis statistik umum. Jadi tanpa package tambahan, anda sudah dapat mulai menggunakannya. Daftar _package_ dan fungsi dasar R dapat dilihat pada situs [R base packages](https://stat.ethz.ch/R-manual/R-devel/library/base/html/00Index.html).    

+ __R IDE__: adalah piranti lunak (aplikasi) terintegrasi. Ada dua jenis yang bisa anda pilih: apakah [R Studio](www.rstudio.com) atau [R Commander](http://www.rcommander.com/). Masing-masing memiliki kelebihan dan kelemahan. Tapi dalam buku ini, kita akan memakai R Studio. R Studio dapat membantu anda menulis skrip kode, menjalankannya, mengevaluasinya, dan membuat visualisasinya.

+ __Package tambahan__: ini adalah pengembangan dari kode dasar R base. Tiap _package_ memiliki kemampuan spesifik, tergantung kepada si pembuatnya. Terdapat ribuan _package_ di server CRAN saat ini. Akan sangat membingungkan. Untuk itu tiap _package_ yang diunggah di CRAN, wajib memiliki dokumentasi atau _manual book_. Dokumentasi tersebut memiliki spesifikasi minimum agar seragam, yang memudahkan para pengguna, yaitu kita para non-programmers. 


## Instalasi R

Sekarang mulailah "pekerjaan kotor kita", yaitu menginstalasi R ke dalam PC atau laptop kita. Untuk itu coba perhatikan beberapa hal berikut ini:

+ Spesifikasi komputer/laptop: Tidak ada spesifikasi khusus untuk R, tetapi prinsip utamanya adalah makin besar data yang anda gunakan, makin kompleks analisis yang anda lakukan, akan memerlukan spesifikasi prosesor dan RAM yang makin besar. Jadi ini akan sangat bergantung kepada kebutuhan anda. Untuk keperluan pembelajaran gunakan saja komputer yang anda miliki sekarang. 

+ Sistem operasi (OS): Seperti yang telah saya sampaikan sebelumnya, R berjalan di semua OS: Linux (bisa Ubuntu, Fedora dll), Mac OS, dan tentunya Windows. Jangan kuatir, yang manapun OS yang anda pakai, spesifikasi R nya akan sama persis. 

+ Apa saja yang perlu anda unduh dan install:

    + R base: Inti dari R. 
        + Kunjungi [Situs R Project](http://www.r-project.org/)
        + Pilih _mirror server_. Pilih server yang ada di Indonesia. Klik `CRAN mirror` di dalam kotak "Getting Started". Cari server di Indonesia. Ada dua, silahkan anda pilih: 
            + [Server BPPT](http://cran.repo.bppt.go.id/) 
            + [Server Universitas Jember](http://cran.unej.ac.id)
        + Setelah server CRAN-BPPT terbuka, klik versi R sesuai dengan OS yang anda miliki.

  + R Studio: lingkungan pemrograman.
    + Kunjungi [Situs R Studio](http://www.rstudio.com/) 
    + Klik menu `Products` > `RStudio` > klik tombol `Download RStudio Desktop`. Secara otomatis R Studio akan membaca OS yang anda pakai dan proses pengunduhan akan segera dimulai.  

Atau

+ Anda bisa langsung buka halaman http://www.rstudio.com/products/rstudio/download/, Pilih versi RStudio. Pilihan _installer_ yang ada per tanggal 04 September 2014 adalah (sekarang pasti sudah berubah banyak):
    + RStudio 0.98.1049 - Windows XP/Vista/7/8	ukuran file 48.2 MB	tanggal update 2014-09-02	
    + RStudio 0.98.1049 - Mac OS X 10.6+ (64-bit)	ukuran file 37.8 MB	tanggal update 2014-09-02
    + RStudio 0.98.1049 - Debian 6+/Ubuntu 10.04+ (32-bit)	ukuran file 56.3 MB	tanggal update 2014-09-02
    + RStudio 0.98.1049 - Debian 6+/Ubuntu 10.04+ (64-bit)	ukuran file 58 MB	tanggal update 2014-09-02
    + RStudio 0.98.1049 - Fedora 13+/openSUSE 11.4+ (32-bit)	ukuran file 56.6 MB	tanggal update 2014-09-02
    + RStudio 0.98.1049 - Fedora 13+/openSUSE 11.4+ (64-bit)	ukuran file 57.9 MB	tanggal update 2014-09-02

Setelah proses pengunduhan selesai, jalankan file program instalasinya:

+ Untuk Linux: jalankan file `xRstudioxx.deb` dan ikuti perintahnya.
+ Untuk Mac OSX: jalankan file `xRstudioxx.dmg` dan ikuti perintahnya
+ Untuk Windows: jalankan file `xRstudioxx.exe` dan ikuti perintahnya

## Menggunakan buku ini

Buku ini merupakan buku tutorial R pertama dalam Bahasa Indonesia. Kami berdua bukanlah programmer. Saya, penulis pertama, berlatar belakang pendidikan geologi dan Prana Ugi, penulis kedua, menyelesaikan pendidikan sarjana dan magisternya di bidang matematika dan statistik. Jadi kami merasakan sulitnya belajar bahasa pemrograman, sehingga kami menggunakan cara yang paling sederhana untuk menjelaskan berbagai fungsi dan operasi R dalam buku ini. Pada banyak tempat kami melakukan pengulangan dan alur cerita yang lambat, yang mungkin akan membosankan bagi para programmer.

Untuk menggunakan buku ini mudah dan sederhana. Kalau anda pemula, maka mulailah dari awal. Tapi kalau anda telah memiliki pengalaman dengan R sebelumnya, dapat kiranya memilih berbagai contoh aplikasi yang kami berikan. Anda cukup menyediakan: 

+ PC atau laptop dengan spesifikasi yang memadai? Saya pernah menginstalasi R di sebuah netbook dengan prosesor yang minim dan ternyata tetap jalan dengan baik. Tentunya data yang anda baca tidak dapat terlalu banyak bila menggunakan laptop jenis ini. 
+ Instalasi R base dan R Studio.
+ Koneksi internet, karena anda akan sering mencoba mencari contoh-contoh lainnya milik orang lain yang telah diunggah di [Rpubs](www.rpubs.com) misalnya, atau anda mencari jawaban atas masalah anda dari [Stackoverflow](www.stackoverflow.com).
+ Anda tidak perlu mengetik ulang kode yang ada dalam buku ini, karena kami menyediakan kodenya secara online di situs [DasaptaErwin](www.dasaptaerwin.net/wp). Copy kode yang ada di situs tersebut sesuai dengan bab dan sub bab yang anda perlukan, kemudian paste ke dalam _script window_ R Studio.

Mudah bukan.


